theme = "cupper-hugo-theme"
baseURL = "https://tuitsarg2019.netlify.app/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "TuitsArg2019"
enableEmoji = true

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:slug/"

[imaging]
  quality = 99

[params]
  description = "An accessibility-friendly Hugo theme, ported from the [original Cupper](https://github.com/ThePacielloGroup/cupper) project."
  footer = "Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Netlify](https://www.netlify.com/)."
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Jan 2, 2006"
  codePenUser = "someUser"

[menu]

  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
    
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 2
