baseURL: https://tuitsarg2019.netlify.app/
languageCode: en-us
defaultContentLanguage: en
title: web_TuitsArg2019
theme: cupper-hugo-theme
#googleAnalytics: UA-123456789-1
#disqusShortname: yourdiscussshortname
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: Aplicación de herramientas de análisis a los tuits de la campaña electoral argentina de 2019.
  homeMetaContent: An accessibility-friendly Hugo theme, ported from the original Cupper project.
  footer: Creado por Carolina Franco con [Hugo](https://gohugo.io/). El tema es de [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Servido con [Netlify](https://www.netlify.com/).
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: true
  moveFooterToHeader: false
  customCss:
    - css/custom_01.css
    - css/custom_02.css
  customJs:
    - js/custom_01.js
    - js/custom_02.js

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Recorrido
      url: /post/
      weight: 2
    - name: About
      url: /about/
      weight: 3
    - name: Tags
      url: /tags/
      weight: 4

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2